name: tangelo
favicon: null
layout_spectrum: 0.532382849836722
typography_spectrum: 0.02195820421911776
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c0afa4'
    - '#fb7925'
    - '#b83e15'
    - '#8d0f0a'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
